name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_ACTOR}" # 3.2.3　デフォルト環境変数
      - run: echo "${{ github.actor }}" # github コンテキストの参照
      - run: echo "${{ github.run_id }}" # github コンテキストの参照
      - run: echo "${{ github.head_ref }}" # github コンテキストの参照
      - run: echo "${{ github.workspace }}" # github コンテキストの参照
      - run: echo "${{ github.repository }}" # github コンテキストの参照
      - run: echo "${{ github.repository_owner }}" # github コンテキストの参照
      - run: echo "${{ github.event.pull_requests.title }}" # github コンテキストの参照
      - run: echo "${{ runner.name }}" # github コンテキストの参照
      - run: echo "${{ runner.os }}" # github コンテキストの参照
      - run: echo "${{ runner.arch }}" # github コンテキストの参照
      - run: echo "${{ runner.temp }}" # github コンテキストの参照
      - run: echo "${{ runner.tool_cache }}" # github コンテキストの参照
      - run: echo "${{ runner.debug }}" # github コンテキストの参照
